# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0e34ef47a0cfc15cfbb36a4b3cf7ca3c6225b9c50db51a9ac3c209933c1ceaab316cbad9731ddb1fb0ed98d00fcda11d4827a00a1e5241584b5bb749279263

test:
  secret_key_base: 757e6e1da42372f11609b1d18b613ef6678266c3f74af581072f03e0ff4e5b0f8a9959a98e5574bd6b2f42dbf39305d9951d967eba971d166b0c9773ed8c5ee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
